# Generated by Django 4.1 on 2023-01-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='sys',
        ),
    ]
